name: Coach Feedback Component Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Core Tests
      run: |
        python test_core.py
        
    - name: Run Database Tests
      run: |
        python test_database.py
    
    - name: Start Server and Run API Tests
      run: |
        # Start server in background
        python main.py &
        SERVER_PID=$!
        
        # Wait for server to start
        sleep 5
        
        # Run API tests
        python quick_test.py
        
        # Stop server
        kill $SERVER_PID
    
    - name: Generate Test Report
      run: |
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        echo "✅ Core Tests: PASSED" >> $GITHUB_STEP_SUMMARY
        echo "✅ Database Tests: PASSED" >> $GITHUB_STEP_SUMMARY
        echo "✅ API Tests: PASSED" >> $GITHUB_STEP_SUMMARY